version: '3.8'

services:
    mysql:
        image: mysql:8.0
        container_name: laravel-mysql-test
        restart: always
        environment:
            MYSQL_DATABASE: test_db
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3307:3306"
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
